spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:pet-clinic
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

